### ISSUE TITLE
Comaptibility with Moodle 3.3?

### ISSUE THREAD

**Issue by adpe** [moodleuulm/moodle-local_maintenance_livecheck#2]
Hello @abias @Kathrin84 

Does this plugin works with Moodle 3.3? :wrench: And why do you have the requirements for your plugins all on min. 3.4? 

We've your plugin https://github.com/moodleuulm/moodle-block_people running on our Moodle 3.3.3+ platform, and it's actually running well. We just checkout to an older "commit", where the version isn't bumped to 3.4. :zap: 

Thanks for your understanding and explanations
Adrian

**Comment by Kathrin84** [comment]
Hi Adrian,
yes, this plugin is running and updated for Moodle 3.3:
https://moodle.org/plugins/pluginversions.php?plugin=local_maintenance_livecheck

You simply need to download the corresponding version and not the latest version from the description page. (Same for block_people: https://moodle.org/plugins/pluginversions.php?plugin=block_people 
altough it is not related to local_maintenance live check.)

You should always take the versions from the Moodle plugins repository if the plugins are published there as those are non dev versions and are tested. If you use the github version you have to check out older commits as we don't work on several stable branches for our plugins.

I hope this helps.
Best, Kathrin

**Comment by adpe** [comment]
Thanks @Kathrin84 

I've see now, that you are working with release tags. I can now simple run this command on a Moodle 3.3 env -> `git checkout tags/v3.3-r4`

Thanks a lot
Adrian
